apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: admin
          - name: GF_SECURITY_ADMIN_USER
            value: admin
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana
spec:
  type: LoadBalancer  # Use NodePort or ClusterIP for internal access
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: grafana